export const TERM = Object.freeze({
  name: "2026-2027 学年第 1 学期",
  startDate: "2026-09-07",
  totalWeeks: 16,
  timeZone: "Asia/Shanghai",
});

export const PERIODS = Object.freeze({
  1: { start: "08:00", end: "08:45" },
  2: { start: "08:55", end: "09:40" },
  3: { start: "10:00", end: "10:45" },
  4: { start: "10:50", end: "11:35" },
  5: { start: "14:30", end: "15:15" },
  6: { start: "15:25", end: "16:10" },
  7: { start: "16:30", end: "17:15" },
  8: { start: "17:25", end: "18:10" },
  9: { start: "19:30", end: "20:15" },
  10: { start: "20:25", end: "21:10" },
});

const range = (start, end) =>
  Array.from({ length: end - start + 1 }, (_, index) => start + index);

const weeks = (...groups) => [...new Set(groups.flat())].sort((a, b) => a - b);

const makeCourse = ({ periodStart, periodEnd, ...course }) => ({
  ...course,
  periodStart,
  periodEnd,
  startTime: PERIODS[periodStart].start,
  endTime: PERIODS[periodEnd].end,
});

// 修改或新增课程只需编辑此列表。activeWeeks 可使用 range(1, 16)
// 表示连续周，也可使用 weeks(range(1, 5), range(10, 14)) 合并多个区间。
export const COURSES = Object.freeze([
  makeCourse({
    id: "linear-algebra-mon",
    name: "线性代数 A",
    weekday: 1,
    periodStart: 1,
    periodEnd: 2,
    activeWeeks: range(10, 16),
    location: "行政楼 304",
    tone: "green",
  }),
  makeCourse({
    id: "electronics-mon",
    name: "电工电子技术",
    weekday: 1,
    periodStart: 5,
    periodEnd: 6,
    activeWeeks: weeks(range(1, 5), range(10, 14)),
    location: "2 教 503",
    tone: "amber",
  }),
  makeCourse({
    id: "policy-tue",
    name: "形势与政策",
    weekday: 2,
    periodStart: 1,
    periodEnd: 2,
    activeWeeks: [14],
    location: "1 教 412",
    tone: "coral",
  }),
  makeCourse({
    id: "linear-algebra-tue",
    name: "线性代数 A",
    weekday: 2,
    periodStart: 3,
    periodEnd: 4,
    activeWeeks: range(10, 15),
    location: "1 教 412",
    tone: "green",
  }),
  makeCourse({
    id: "mechanics-tue",
    name: "理论力学",
    weekday: 2,
    periodStart: 5,
    periodEnd: 6,
    activeWeeks: weeks(range(1, 5), range(10, 16)),
    location: "土木楼南楼 419",
    tone: "blue",
  }),
  makeCourse({
    id: "mao-tue",
    name: "毛泽东思想和中国特色社会主义理论体系概论",
    shortName: "毛概",
    weekday: 2,
    periodStart: 7,
    periodEnd: 8,
    activeWeeks: range(1, 16),
    location: "1 教 110",
    tone: "red",
  }),
  makeCourse({
    id: "electronics-wed",
    name: "电工电子技术",
    weekday: 3,
    periodStart: 5,
    periodEnd: 6,
    activeWeeks: weeks(range(1, 5), range(10, 14)),
    location: "1 教 306",
    tone: "amber",
  }),
  makeCourse({
    id: "mao-online-wed",
    name: "毛泽东思想和中国特色社会主义理论体系概论",
    shortName: "毛概（线上）",
    weekday: 3,
    periodStart: 9,
    periodEnd: 10,
    activeWeeks: [9, 11, 13, 15],
    location: "线上课程",
    online: true,
    tone: "red",
  }),
  makeCourse({
    id: "linear-algebra-thu",
    name: "线性代数 A",
    weekday: 4,
    periodStart: 1,
    periodEnd: 2,
    activeWeeks: range(10, 16),
    location: "1 教 210",
    tone: "green",
  }),
  makeCourse({
    id: "xi-online-thu",
    name: "习近平新时代中国特色社会主义思想概论",
    shortName: "习概（线上）",
    weekday: 4,
    periodStart: 9,
    periodEnd: 10,
    activeWeeks: [9, 11, 13, 15],
    location: "线上课程",
    online: true,
    tone: "purple",
  }),
  makeCourse({
    id: "mechanics-fri",
    name: "理论力学",
    weekday: 5,
    periodStart: 1,
    periodEnd: 2,
    activeWeeks: weeks(range(1, 5), range(10, 16)),
    location: "土木楼南楼 420",
    tone: "blue",
  }),
  makeCourse({
    id: "policy-fri",
    name: "形势与政策",
    weekday: 5,
    periodStart: 3,
    periodEnd: 4,
    activeWeeks: [14],
    location: "2 教 301",
    tone: "coral",
  }),
  makeCourse({
    id: "xi-fri",
    name: "习近平新时代中国特色社会主义思想概论",
    shortName: "习概",
    weekday: 5,
    periodStart: 5,
    periodEnd: 6,
    activeWeeks: range(1, 16),
    location: "2 教 301",
    tone: "purple",
  }),
  makeCourse({
    id: "pe-fri",
    name: "大学体育与健康（3）",
    weekday: 5,
    periodStart: 7,
    periodEnd: 8,
    activeWeeks: range(1, 16),
    location: "地点待定",
    tone: "teal",
  }),
]);

export const PRACTICE_COURSES = Object.freeze([
  {
    id: "metalworking-practice",
    name: "金工实训 C",
    activeWeeks: range(6, 9),
    note: "本周实践课程",
  },
]);
